events {}

http {
  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # SPA 支持
    location / {
      try_files $uri /index.html;
    }

    # Martin (MVT)
    location /tiles/ {
      proxy_pass http://martin:3000/;
    }

    # GeoServer (WMS)
    # location /geoserver/ {
    #   proxy_pass http://geoserver:8080/geoserver/;
    # }

    # glyphs
    location /glyphs/ {
      add_header Access-Control-Allow-Origin *;
    }

    # sprites
    location /sprites/ {
      add_header Access-Control-Allow-Origin *;
    }

    # gzip
    gzip on;
    gzip_types application/json application/x-protobuf;
  }
}